name: Caching

on: push

jobs:
  node_cache:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm ci
    - run: npm install serverless

  python_cache:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ hashFiles('requirements.txt') }}
    - run: ls ~/.cache/pip
    - name: Install requirements
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt
        pip install --upgrade --upgrade-strategy eager -r test-requirements.txt

  validate:
    needs: python_cache
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install requirements
      run: |
        pip install nose2
        pip install flake8
    - run: ls ~/.cache/pip
    - name: linting
      run: flake8 --extend-ignore=E501 app/
    - name: unit tests
      run: nose2 --with-coverage --coverage ../../app/

  dev_deploy:
    if: startsWith(github.ref, 'refs/heads/feature/')
    needs:
    - validate
    - node_cache
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: node cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: deploy static content
      run: ./node_modules/serverless/bin/serverless.js client deploy --no-confirm
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
        RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
        USE_RECAPTCHA_FOR_GUEST: True
        USE_RECAPTCHA_FOR_ADMIN: True
        FLASK_SECRET: ${{ secrets.FLASK_SECRET }}
        ADMIN_PASSWORD_HASH: ${{ secrets.ADMIN_PASSWORD_HASH }}
        WEB_DOMAIN: ${{ secrets.WEB_DOMAIN }}
        HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
        PERSONALIZE_SRC_FILE: app/personalize/rsvp_content.yaml
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
    - name: serverless deploy
      run: ./node_modules/serverless/bin/serverless.js deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
        RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
        USE_RECAPTCHA_FOR_GUEST: True
        USE_RECAPTCHA_FOR_ADMIN: True
        FLASK_SECRET: ${{ secrets.FLASK_SECRET }}
        ADMIN_PASSWORD_HASH: ${{ secrets.ADMIN_PASSWORD_HASH }}
        WEB_DOMAIN: ${{ secrets.WEB_DOMAIN }}
        HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
        PERSONALIZE_SRC_FILE: app/personalize/rsvp_content.yaml
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}